baseURL: https://elhq.netlify.app/
languageCode: en-us
paginate: 6
theme: portio-hugo
title: ELHQ Solicitors
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: Meet our Team
      url: '#resume'
      weight: 2
    - name: Case studies
      url: '#portfolio'
      weight: 3
    - name: Insights
      url: '#blog'
      weight: 4
    - name: Testimonials
      url: '#testimonial'
      weight: 5
  sitemap:
    - name: Cookies Policy
      url: '#'
      weight: 1
    - name: Frequently Asked Questions
      url: '#'
      weight: 2
    - name: Privacy & Policy
      url: '#'
      weight: 3
    - name: Careers at ELHQ
      url: '#'
      weight: 4
params:
  address:
    address: 1 Percy Place, Dublin 2, Dublin.
    email: info@elhq.com
    openingHours: Open from 10am to 6pm 
    phone: +(353) 86 860 8807
  blogPageURL: blog
  contactLink: contact
  copyright: All right reserved copyright © Kieran Lardner 2020
  footerLogo: images/site-navigation/logo2.png
  formspreeURL: YOUR FORMSPREE URL
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo2.png
  map:
    APIkey: AIzaSyCzbR0U-eFsOhFP9v8Zr7IMQkHRXhTiLdA
    latitude: '53.337312'
    longitude: '-6.240286'
    pinImage: images/pin.png
  social:
    - icon: fa-facebook-official
      url: https://www.facebook.com/ELHQ-Solicitors-108084114825528
      weight: 1
    - icon: fa-twitter-square
      url: https://twitter.com/ElhqSolicitors
      weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true
